//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseDateTime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public courseDateTime()
        {
            this.courses = new HashSet<cours>();
        }
    
        public int ID { get; set; }
        public int courseID { get; set; }
        public int courseDate1 { get; set; }
        public Nullable<int> courseDate2 { get; set; }
        public Nullable<int> courseDate3 { get; set; }
        public Nullable<int> courseDate4 { get; set; }
        public Nullable<int> courseDate5 { get; set; }
        public int courseTime { get; set; }
    
        public virtual cours cours { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cours> courses { get; set; }
    }
}
