//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1_Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class baron_project1Entities : DbContext
    {
        public baron_project1Entities()
            : base("name=baron_project1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<courseDateTime> courseDateTimes { get; set; }
        public virtual DbSet<cours> courses { get; set; }
        public virtual DbSet<professor> professors { get; set; }
        public virtual DbSet<professorCourseList> professorCourseLists { get; set; }
        public virtual DbSet<student> students { get; set; }
        public virtual DbSet<studentCourseList> studentCourseLists { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
