//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1_Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class professorCourseList
    {
        public int professorCourseListID { get; set; }
        public int professorID { get; set; }
        public int studentID { get; set; }
        public int courseID { get; set; }
    
        public virtual cours cours { get; set; }
        public virtual professor professor { get; set; }
        public virtual student student { get; set; }
    }
}
